project:
  type: website
  output-dir: docs

website:
  title: "Elisa Pierfederici"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Teaching.qmd
        text: Teaching
      - href: Projects.qmd
        text: Projects
      - href: Blog.qmd
        text: Blog
    page-footer:
      background: light
      left:
        - "Copyright 2023, Elisa Pierfederici"
      right:
        - icon: LinkedIn
          href: https://www.linkedin.com/in/maria-elisa-pierfederici-5392aa182/
        - icon: GitHub
          href: https://github.com/mariapie

format:
  html:
    theme:
      light: minty
      dark: Sandstone
    css: styles.scss
    page-layout: full




