project:
  type: website
  output-dir: docs

website:
  title: "Elisa Pierfderici"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Blog.qmd
      - Projects.qmd

format:
  html:
    theme: 
      light: minty
      dark: Sandstone
    css: styles.css
    page-layout: full



