project:
  type: website
  output-dir: docs

website:
  title: "Elisa Pierfderici"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - Teaching.qmd
      - Projects.qmd
      - Blog.qmd
    page-footer: 
    background: light
    left: 
      - "Copyright 2023, Elisa Pierfederici"
    right:
    - icon: LinkedIn
      href: https://www.linkedin.com/in/maria-elisa-pierfederici-5392aa182/
    - icon: GitHub
      href: https://github.com/mariapie
    
format:
  html:
    theme: 
      light: minty
      dark: Sandstone
    css: styles.css
    page-layout: full



